version: '2'
services:
  mosquitto:
    image: ncarlier/mqtt
    volumes:
      - /var/lib/docker/volumes/mosquitto/config:/etc/mosquitto
      - /var/lib/docker/volumes/mosquitto/data:/var/lib/mosquitto
      - /var/lib/docker/volumes/mosquitto/log:/var/log/mosquitto
    ports:
    {{- if (.Values.MQTT_PORT) }}
      - ${MQTT_PORT}:1883
    {{- end }}
    {{- if (.Values.MQTT_SSL_PORT) }}
      - ${MQTT_SSL_PORT}:8883
    {{- end }}
    restart: always