version: '2'
services:
  samba:
    image: dperson/samba
    restart: always
    network_mode: "host"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - /var/lib/docker/volumes/ha_config:/config
    environment:
      TZ: CET
      WORKGROUP: WORKGROUP
    command: -u "${USERNAME};${PASSWORD}" -s "Config;/config;yes;no;no;${USERNAME};${USERNAME}" -n -p