version: '2'

.catalog:
  name: Samba
  description: |
    This samba mounts your home assistant config so you can edit it from a remote
  version: 1.0.2
  questions:
   - variable: 'USERNAME'
     description: 'Enter a username for samba'
     label: 'Username'
     required: true
     type: 'string'
     default: default
   - variable: 'PASSWORD'
     description: 'Enter a password for samba'
     label: 'Password'
     required: true
     type: 'password'
     default: default
   - variable: 'SHARENAME'
     description: 'Enter the name of the samba share'
     label: 'Share name'
     required: true
     type: 'string'
     default: haconfig
   - variable: 'HOST_FOLDER'
     description: 'Enter the host folder path'
     label: 'Folder path'
     required: true
     type: 'string'
     default: /var/lib/docker/volumes/ha_config
   - variable: 'SHARENAME2'
     description: 'Enter the name of the second samba share (leave empty to skip)'
     label: 'Share name 2'
     required: false
     type: 'string'
     default: mosquitto
   - variable: 'HOST_FOLDER2'
     description: 'Enter the second host folder path'
     label: 'Folder path 2'
     required: false
     type: 'string'
     default: /var/lib/docker/volumes/mosquitto